os: osx
osx_image: xcode10.2
language: generic
before_script:
- brew update
- brew install --HEAD usbmuxd
- brew unlink usbmuxd
- brew link usbmuxd
- brew unlink python@2
- brew link --overwrite python
- brew install --HEAD libimobiledevice
- brew install ideviceinstaller
- brew install ios-deploy
- git clone https://github.com/flutter/flutter.git -b beta --depth 1
script:
- flutter/bin/flutter build ios --debug --no-codesign
cache:
  directories:
  - "$HOME/.pub-cache"
before_deploy:
- pushd build/ios/iphoneos
- mkdir Payload
- cd Payload
- ln -s ../Runner.app
- cd ..
- zip -r app.ipa Payload
- popd
deploy:
  provider: releases
  api_key:
    secure: oiodnHwOTSTYoyt8oJTP1GvbbB+glfDhYhfFq8VFS66pXy/6MwdPtF2Oi6IAh4O+5tvCUVn2bFYDjFEAiT6COCFgsetdytOcORLC1pUCRpaVJ1eZSmFdm7tzgaR8FAkDKurvgMwiESz1fkZelTr2igoEMHEZ8TLmZaJh1JJ0JJItRflKgTY30ayttQUsnInLpQ8ZElK7tI9I2U6G8pq3+OLx5r8Chu+Xq3N3Xpr7IL50w9HeKe+lJZ3C8GmkPh+QUutKMXQ2+ePp8aDIoZeg6lFvxBhFPAoBFz6kJ/brUL7UKlxw4/R6k436WLcPaqCNn69WNIAgshk30e8QOtqYeL9HClcpKTFPemP3NGbgJ7j5sYcv9xXkw7Zm8UTiO7VrMST40K5/N4gY/VZ2kQZFDFsZ5GgpH9C0mucX8/UO3NTQDmfUnc5XNA5w6cwUG0eYCE+i3yNCLFDD7M07iJQOj/CPrapV/k9o2J/rVlY51bptcXuh9mBeLKBGIraPSRG3Yfi//gekKKyVqy7O2znYxdTxhZR2uVnmYUmnbu83t+/yfgMYWzb3f5lio5tJfiYkVwEIDtWOXCwv/5qFpFgRMRtAULDR+NVcTuuc4aic4D0QsClbe0oarFotr3vLeLOAPoqDVw0FilsrVNv+r7hW20GQpWg7BWAdPWg3yProS+4=
  file: build/ios/iphoneos/app.ipa
  skip_cleanup: true
